name: travelbuddy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  dropdown_button2: ^2.3.9
  dotted_border: ^2.1.0
  path_provider: ^2.0.0
  image_picker: ^1.1.2
  dropdown_search: ^5.0.6
  shared_preferences: ^2.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.7

flutter:
  uses-material-design: true
